# Generated by Django 5.0.6 on 2024-05-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
